support for downloading remote dependencies from vendor packages
dhillondeep/wcosa pull request #62
Opened 2018-07-18 16:57 UTC by dhillondeep

This is basically what I did:
1. Ignore vendor dependency from the project dependencies
2. Scan vendor dependencies and create a map of all the remote dependencies in them
3. Merged these dependencies with the project's remote dependencies
4. Then remote fetcher fetches all the remote dependencies
5. Removed path checking for vendor packages (remote fetcher does not know anything about vendor)

More details:
* Remote will fetch all remotes and that is it
* Build process will create a dependency tree and resolve overrides from vendor

2018-07-18 22:08 UTC, dhillondeep commented
Let's talk about this in meeting today

2018-07-18 22:46 UTC, Mogball requested changes

2018-07-18 22:46 UTC, Mogball commented on tests/runtests.sh
> +    wio install
build?

2018-07-18 22:46 UTC, Mogball commented on tests/runtests.sh
we don't need the .gitkeep

2018-07-18 22:46 UTC, Mogball commented on tests/project-app/app-avr-vendor/.gitignore
> +.wio/
don't push the generated .gitignore

2018-07-18 22:46 UTC, Mogball commented on tests/project-app/app-avr-vendor/README.md
> +# app-avr-vendor
don't push the generated README

2018-07-18 22:46 UTC, Mogball commented on cmd/wio/types/general-types.go
> +            depMap[name] = io.Vendor + dep.Version
do you want separator between these?

2018-07-18 22:46 UTC, Mogball commented on cmd/wio/toolchain/npm/resolve/resolve.go
> +                log.Warnln(queue, "vendor dependency [%s] is supposed to be a package. Skipping....",
don't use the queue it makes code kinda messy...

2018-07-18 22:46 UTC, Mogball commented on cmd/wio/toolchain/npm/resolve/resolve.go
> +                log.Warnln(queue, "vendor dependency [%s] is supposed to be a package. Skipping....",
and this should cause an error

2018-07-18 22:46 UTC, Mogball commented on cmd/wio/toolchain/npm/resolve/resolve.go
> +        if strings.Contains(ver, io.Vendor) {
versions will never contain "vendor" since it's an invalid version string, shouldn't you use the Vendor flag?

2018-07-18 22:46 UTC, Mogball commented on cmd/wio/toolchain/npm/resolve/resolve.go
> +    if err := FlattenVendorRemoteDependencies(queue, i.dir, vendorRemotes); err != nil {
classic deep coding style super long names

2018-07-19 21:40 UTC, Mogball commented
@dhillondeep can this be closed?

2018-07-19 21:40 UTC, Mogball commented
oops closed it

2018-07-20 03:06 UTC, closed without merging